### PR TITLE
Esther/tooltip

### PR DESCRIPTION
**Pull request by eswitbeck**
Create tooltip which follows mouse, keeps a z index over the queries, and stays within the bounds of the graph.

Rewrite rerender logic to a switch -- store previous selections for switching off and on. Remove selection graph rerenders to avoid resetting position of tooltip.

### CODE REVIEW

**Review by brand0n-y00n — CHANGES_REQUESTED** [review]
Nice Work! 
tooltip is popping up nicely

There is a duplicate code on lines 146-147
image
double check if deleting one of them still doesn't break the code. Otherwise nice work!

also, like u suggested, we might want to merge my feature branch first before merging this one to resolve any conflicts

**Review by ectjon — APPROVED** [review]
Looks great! tested the tooltip and it works perfectly

**Review by brand0n-y00n — APPROVED** [review]
nice work!

**Review by brand0n-y00n — APPROVED** [review]
nice work!

**Comment by eswitbeck** [comment]
Branch needs bug resolution with tooltip covering queries before merging

**Review by ectjon — COMMENTED** [review]
Looks good!

**Pull request merged**
