### PR TITLE
Brandon/axis titles

### PR DESCRIPTION
**Pull request by brand0n-y00n**
created labels for each of the x-axis and y-axis
changed the values for margins right and height to fit the labels into svg graph

### CODE REVIEW

**Review by ectjon — CHANGES_REQUESTED** [review]
Looks good! I tested the labels and they display as expected.

Would it make sense to chain the label creating function to the axis creation so they're grouped better? See the attached image for example

Screenshot 2023-05-22 at 2 10 15 PM

**Review by eswitbeck — CHANGES_REQUESTED** [review]
Nicely done! The titles look quite tidy.

A comment first: I notice you're making notes of your changes in the comments of the actual document. That's not a bad practice, but I think the body of commit messages might be more suited to it.
e.g.
```
commit -m 'add axis titles to graph
>
> Increased rawHeight from 200 to 300; &c...'

```
I also saw on Timeline:46 the 'shorten' comment, but I'm not seeing that actual change. Was that intentional? It looks instead like we went from 225 computed to 250.

Two minor requests for changes:

1. Since we'll be reformatting our timeline to take a variety of units (I don't think we want the 900,000 displayed on one of my sessions left open), we should probably get rid of the '(ms)' included on the axis.
2. I'm finding the calculations a little difficult to read. Could you refactor those a bit--especially finding alternatives to negatives prepended (-width has a habit of hiding the -) and giving space between each operator? (e.g. width/2 -> width / 2)

**Review by eswitbeck — APPROVED** [review]
Thanks much!

**Review by ectjon — APPROVED** [review]
Looks good!

**Pull request merged**
